### ISSUE TITLE
Load by URI

### ISSUE THREAD

**Issue by justinlittman** [LD4P/sinopia_editor#1033]
When search was added, loading by URI was removed. Per @michelleif it should still be available. Perhaps on the load tab?

**Comment by michelleif** [comment]
@justinlittman @jermnelson  can we get this into release 3.5 so that we are not releasing something that is missing a feature that used to be there?

I think it should be on the search tab. can you just put it back how it was, above or to the side of the search box. @astridu ?

If it's on the load tab, people might think they are loading in the existing URI to create a "clone". because when you use the load tab, you're creating a new resource.

**Comment by michelleif** [comment]
if necessary we can do this after 3.5

**Comment by michelleif** [comment]
on second thought I moved this to backlog because we have other more pressing things to do. user can always put trellis URI into a browser to see the description
