### ISSUE TITLE
Tab and Enter keys don't behave as expected in Title field

### ISSUE THREAD

**Issue by jbaxmeyer** [LD4P/sinopia_editor#1250]
expected behavior: tab to field and press enter to begin entering data; what happened: tab to field and press enter, the arrow expands the field but the cursor isn't in the text box; if you just keep tabbing without pressing Enter, the text box doesn't open; was NOT able to enter a second title

**Comment by michelleif** [comment]
@astridu when you tab to an Add button and press enter, the section expands, and you have to click tab again to actually enter the field. is this expected behavior?

@jbaxmeyer tabbing without pressing enter: expected behavior is to continue to next section. would you want each section to open as you tab to it? without having to press enter?

**Comment by astridu** [comment]
@michelleif It is expected behavior from an accessibility point of view, but I can see how this could be annoying in the long run. We can change the behavior as @jbaxmeyer described.

**Comment by justinlittman** [comment]
The tab behavior works the same as the click behavior, so if I understand correctly this is really about behavior when the +Add button is executed.

While it seems straight-forward in the case where there is a single input box after clicking +Add, in many cases there will not be a single input box, e.g., there may be an entire nested resource template. Given this, I'd suggest that the current behavior is correct.
