### ISSUE TITLE
Variant Title becomes Main Title

### ISSUE THREAD

**Issue by threadleaf** [LD4P/sinopia_editor#1264]
I entered a Variant title, which came out in the RDF as Main title; so did what I entered as a Main title, thus the RDF has two Main titles.

**Comment by jermnelson** [comment]
Hi @threadleaf, 
Did you publish the RDF that exhibits this behavior? The `Harvard:rt:test:userfeedback:instance` that is being used in the user feedback testing includes four embedded resource templates related to the "http://id.loc.gov/ontologies/bibframe/title" property: `sinopia:resourceTemplate:bf2:Title`,
`sinopia:resourceTemplate:bf2:Title:VarTitle`, `sinopia:resourceTemplate:bf2:ParallelTitle`, and `sinopia:resourceTemplate:bflc:TranscribedTitle`. 

The `sinopia:resourceTemplate:bf2:Title` and `sinopia:resourceTemplate:bf2:Title:VarTitle` both have "http://id.loc.gov/ontologies/bibframe/mainTitle" as a property . The `bf:mainTitle` is used as the predicate with the object being the literal value and the subject being a blank node which is why I believe you're seeing the duplicate `bf:mainTitle` in the RDF. 

Here is an example I created that shows the two `bf:mainTitle` associated with the two different blank nodes that have different rdf types for the BF Instance:
```
@prefix bf: <http://id.loc.gov/ontologies/bibframe/> .
@prefix ns1: <http://> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix sinopia: <http://sinopia.io/vocabulary/> .
@prefix xml: <http://www.w3.org/XML/1998/namespace> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

<> a bf:Work ;
    ns1:fakepropertyforusertesting2 "Thanks for testing!"@en ;
    bf:hasInstance [ a bf:Instance ;
            bf:carrier <http://id.loc.gov/vocabulary/carriers/nc> ;
            bf:issuance <http://id.loc.gov/vocabulary/issuance/mono> ;
            bf:media <http://id.loc.gov/vocabulary/mediaTypes/n> ;
            bf:title [ a bf:Title ;
                    bf:mainTitle "The Title Proper"@en ;
                    sinopia:hasResourceTemplate "sinopia:resourceTemplate:bf2:Title" ],
                [ a bf:VariantTitle ;
                    bf:mainTitle "Fun for the title"@en ;
                    sinopia:hasResourceTemplate "sinopia:resourceTemplate:bf2:Title:VarTitle" ] ;
            sinopia:hasResourceTemplate "Harvard:rt:test:userfeedback:instance" ] ;
    sinopia:hasResourceTemplate "Harvard:rt:test:userfeedback" . 
```

**Comment by threadleaf** [comment]
I think I did publish.  Unfortunately, I don’t understand RDF well enough to follow your explanation and example, but it’s enough to know that what I noticed is not actually a problem.
mjc

**Comment by michelleif** [comment]
closing this since mainTitle was part of the variantTitle node, so the RDF is as expected
