### ISSUE TITLE
support multiple lookup sources for inputListLOC

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#1332]
currently, a Property Template with type = lookup supports having more than one useValuesFrom lookup source when the lookups are those that use inputLookupQA

users expect to do the same with inputListLOC lookups.

Example (provided by @sfolsom ):
the property bf:soundCharacteristics has acceptable values in all of these lists:
"https://id.loc.gov/vocabulary/mrectype",
"https://id.loc.gov/vocabulary/mrecmedium",
"https://id.loc.gov/vocabulary/mgroove",
"https://id.loc.gov/vocabulary/mplayspeed",
"https://id.loc.gov/vocabulary/mplayback",
"http://id.loc.gov/vocabulary/mspecplayback",
"https://id.loc.gov/vocabulary/mcapturestorage"

if you try to add multiple useValuesFrom now, you get the error "There are multiple configured list lookups for [propertyURI]"

Instead, allow multiple LOC-list-style lookups for one property template. Handle them like we handle multiple QA lookups, that is, showing a separate set of results from each lookup source.

Unknown whether we need to support a property template that has lookups to both QA-style and LOC-list style lookups.

**Comment by michelleif** [comment]
alternative strategy: change LOC list lookups to QA (would need QA support) and dispense with this component, which would also obviate part of #1188

**Comment by sfolsom** [comment]
Michelle has captured the issue I ran into well. I'd just add that this is a great example of where separate property templates for the rdf property would be ideal. BF has a single property (bf:soundCharacteristics) design to link to different types of characteristics for sound recordings (record groove, playing speed, etc.), and it would be better to have separate fields with their own labels in the editor so that the cataloger knows to capture each of those traits, rather than a single generic "sound characteristics" field that needs to be repeated for each characteristic. (I realize this would require the editor to examine the resource in the object position before loading data into the right field, or for data created by Sinopia tracking the property template that created it.)

**Comment by michelleif** [comment]
so in this example, the ability to have multiple fields using the same propertyURI is so you can give the cataloger different instructions with each, and offer a different lookup source for each? is there anything else that differs among each use of the property? would the generated RDF going to look the same for each use?
<recording> <bf:soundCharacteristics> <literal or uri>

**Comment by justinlittman** [comment]
@michelleif will check progress on getting all LOC lookups into QA. Then can deprecate InputListLOC component.

**Comment by justinlittman** [comment]
Plan is to implement as described in this ticket, rather than add lookups to QA.

**Comment by michelleif** [comment]
tested this on DEV with RT test:multiple:inputLOC and is fixed.
