### ISSUE TITLE
Make display of lookup values consistent 

### ISSUE THREAD

**Issue by alexiskeely** [LD4P/sinopia_editor#1369]
Entered lookup values have inconsistent appearance in base RT and nested RTs.

Entered values in nested RTs don't have a blue outline, making it appear as though no value has been selected, even though the URI appears in preview RDF. There should be some way of indicating that a value has been selected.

Example below is from WAU RT RDA Work monographs, loaded in dev.

![image](https://user-images.githubusercontent.com/37376659/65625048-e9ed6280-df7f-11e9-9da6-fbe5be00b9cd.png)

**Comment by michelleif** [comment]
@alexiskeely this appears to be the same problem as https://github.com/LD4P/sinopia_editor/issues/1285

if you look at the nested template alone (WAU:RT:RDF:list), it shows the same "non-blue" look. the non-blue look is due to it being a field that has repeatable set to false.

if you agree that fixing 1285 will fix this, then please close this one and thank you for reporting this as additional example

as a side note: are you trying to allow cataloger to compose a multi-part subject here? there is a request for support for this here https://github.com/LD4P/sinopia_editor/issues/1312, please comment there if it's something you need. further

**Comment by alexiskeely** [comment]
Same problem as #1285.
