### ISSUE TITLE
Change add field link

### ISSUE THREAD

**Issue by justinlittman** [LD4P/sinopia_editor#1457]
As shown in https://github.com/LD4P/sinopia/issues/261#issuecomment-531882451.

Note that this is for "add", not "add another".

**Comment by justinlittman** [comment]
![image](https://user-images.githubusercontent.com/588335/68501007-15c06100-022b-11ea-9d0d-dc30a7f4d2b6.png)

becomes

![image](https://user-images.githubusercontent.com/588335/68501131-61730a80-022b-11ea-9eb8-6a25d4d00256.png)

**Comment by peetucket** [comment]
Using the "Parallel Title" RT as an example (`ld4p:RT:bf2:ParallelTitle`), and adding multiple "Notes", is it the link shown below (currently showing "Add Note Text", replaced with a more simple "add"?)![Screen Shot 2019-11-11 at 11.47.08 AM.png](https://images.zenhubusercontent.com/59b9a35fb0222d5de477a1fb/e569eaf7-aa58-4b6d-bb7f-31ceec85f851)

**Comment by justinlittman** [comment]
@astridu ?

**Comment by astridu** [comment]
This design is what we're aiming for: https://invis.io/2XTVOZ1KPJM#/382342971_Panels_UI
The field label appears, and then an "+Add" link appears next to it. 

However, if we're going to continue to use the pattern above, you'll need to keep the "Note Text" part so the user knows what they're adding.

**Comment by peetucket** [comment]
I'm finding it challenging to move that "Add" link directly to the right of field name.  I've got the "Add another" link listed in https://github.com/LD4P/sinopia_editor/issues/1718 reasonably close to what is shown and have the trash icons working.  See screen shots below from my laptop

The reason it is a challenge to move the "Add" link right next to field name is the way the react components are nested and the fact that clicking the "Add" link replaces its contents with the box containing the value.  If I move the Add link, the text box goes with it since they appeared to be tied to the same react component.  

So I guess the question is, how much effort do we want to expand on editing the component (as opposed to just the text and css) to make this work?

![Screen Shot 2019-11-12 at 2.07.14 PM.png](https://images.zenhubusercontent.com/59b9a35fb0222d5de477a1fb/6b8db44f-3e1a-4fa1-8808-1773e39e5181)

 ![Screen Shot 2019-11-12 at 2.04.43 PM.png](https://images.zenhubusercontent.com/59b9a35fb0222d5de477a1fb/e51569af-5e9f-4256-98e0-b1ef916c1c72)

**Comment by astridu** [comment]
Got it. It's not ideal, but will work as is.

**Comment by peetucket** [comment]
ok
