### ISSUE TITLE
Validate that value template refs are not ""

### ISSUE THREAD

**Issue by justinlittman** [LD4P/sinopia_editor#1599]
![SAG_resourceTemplate_bf2_Serial_Work_json_—___Downloads](https://user-images.githubusercontent.com/588335/67316688-e85b7f80-f4d6-11e9-9454-8d359234b0a1.png)

results in an error message:
`There was a problem retrieving SAG:resourceTemplate:bf2:Serial:Work: The following referenced resource templates are not available in Sinopia: `
which is not helpful.

**Comment by michelleif** [comment]
The way this empty value gets into the Resource Template in the first place is that in the Profile Editor, you delete an existing valueTemplateRef value by just removing the string rather than using the trash can to delete it.
![Screen Shot 2019-10-22 at 11 56 13 AM](https://user-images.githubusercontent.com/23069165/67320571-40888680-f4c3-11e9-8634-1746dc419620.png)

So perhaps for future we would not let this empty value be created in the first place, by doing something to prevent that in the Profile Editor.

**Comment by peetucket** [comment]
Is there an example profile or RT file that can be attached to this ticket to help reproduce the behavior?

**Comment by michelleif** [comment]
I put an RT in DEV for you: blank:valuetemplateref
and also attaching here a  Profile that contains it
[ProfileBlankValueTemplateRef.json.txt](https://github.com/LD4P/sinopia_editor/files/3786485/ProfileBlankValueTemplateRef.json.txt)

**Comment by peetucket** [comment]
Ok, thanks.  So the error is when you try to create a new instance from the RT (I was confused and thought it was when you first try to import the RT).  I got a slight variation on the error, but presume its the same thing:

```There was a problem retrieving blank:valuetemplateref: TypeError: Object(...)(...).then is not a function```

**Comment by justinlittman** [comment]
Opening, not importing.

**Comment by peetucket** [comment]
OK, that's what I saw as well.  Though the text of the error I saw was different than the original screenshot.
