### ISSUE TITLE
Missing resource templates in production

### ISSUE THREAD

**Issue by a-cohen** [LD4P/sinopia_editor#1646]
Potentially not a bug, but an oversight.

There seem to be some missing LD4P resource templates in the production environment. When I try to open ld4p:RT:bf2:Monograph:Item I get this error message: 
![Capture](https://user-images.githubusercontent.com/45469510/67813338-e5c4d100-fa66-11e9-8385-d1714f758c3c.PNG)
And when I open the Agent property in ld4p:RT:bf2:Agents:Contribution I get this:
![Capture1](https://user-images.githubusercontent.com/45469510/67813481-3f2d0000-fa67-11e9-8001-a614d4b351ea.PNG)

The missing RTs don't appear to be listed in the list of available resource templates on stage.

I've checked production using both Firefox and Chrome and that doesn't seem to change anything.
--

**Comment by michelleif** [comment]
thanks Adam, are you saying these resource templates existed on production at one point, and are now gone?

**Comment by a-cohen** [comment]
Hi Michelle, yes at one point they were available on production (and still seem to be on stage).

**Comment by michelleif** [comment]
strange. well, instead of trying to figure out what happened, I just imported the 2 profiles containing the missing templates into Production (https://github.com/LD4P/ld4ptemplates/blob/master/LD4P%20BIBFRAME%202.0%20Item.json and https://github.com/LD4P/ld4ptemplates/blob/master/LD4P%20BIBFRAME%202.0%20RWO.json) 

should work now. please close this ticket if things seem okay now.

**Comment by a-cohen** [comment]
Works great! Closing now
