### ISSUE TITLE
add facets for Sinopia search

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#1696]
add facets to allow user to filter search results by type or by group

see design in https://github.com/LD4P/sinopia/issues/90

**Comment by michelleif** [comment]
combining facets: AND, OR?
do we allow NOT?
display counts? NO.
how many values per facet? in what order?

RESOLVED: Justin Coyne and Astrid to discuss other ways to implement like with filtering

**Comment by astridu** [comment]
![image](https://user-images.githubusercontent.com/42216982/68986026-2eeb8380-07d0-11ea-981b-c26c12f7a122.png)

**Comment by astridu** [comment]
I looked at a few different filtering examples of filtering on the web, and sites are using the dynamic option to narrow the filter where it's obvious a user wouldn't want to search on more than one of the filter options, but then leave some of the other options as checkboxes because users may want to select multiple of those options. 

If a user may want to select multiple Class or Institution, then they should not be dynamic, users should be able to select multiple w/o it dynamically removing options.

**Comment by justinlittman** [comment]
According to @michelleif, multi is preferred.
