### ISSUE TITLE
Investigate undo

### ISSUE THREAD

**Issue by justinlittman** [LD4P/sinopia_editor#1717]
In particular, within the editor tab allowing the user to undo the last action performed.

Please spend up to several hours on this.

**Comment by jgreben** [comment]
A place to start: https://redux.js.org/recipes/implementing-undo-history

**Comment by jgreben** [comment]
There is a library to make it easier to implement: https://github.com/omnidan/redux-undo

**Comment by jgreben** [comment]
What is the UI design for un-doing action in the editor tab? Seems like it would be a top-level feature since all of the specific form actions are already un-doable (i.e. removable) by themselves. 

As a top-level feature, implementing `redux-undo` would be concerned with removing the `selections`, `items`, and resources from state, so everything relevant will have to be wrapped with redux-undo's `undoable`, e.g. `addResource`, `removeResource`, `setItemsOrSelections`, and other reducers. Then, according to redux-undo we would add a dispatch to the top-level Editor component.

IMO Seems like implementing undo with redux-undo might obviate the need to retain all of the current distinct remove actions, so if we do this it would probably be good to clean up/refactor the code and not have two different ways to remove/undo actions.

**Comment by jgreben** [comment]
By implementing redux-undo it wraps the `selectorReducer` state with 
```
{ past: [ pastStates...], present: { state...}, future: [ futureStates...] }
```
AFAIKT at the moment, this means that everywhere we have hard-coded, e.g. `state.selectorReducer....` would need to change to `state.selectorReducer.present....`

From my experimentation, applying `undoable` to either the top-level `appReducer` or lower-level state calls such as `setItemsOrSelections` has the same effect: it still wraps the entire `selectorReducer` in `{ past: [], present: {}, future: [] }`

**Comment by jgreben** [comment]
Implementing undo will be complex. The way we update state in the app causes a lot of duplicative history entries and consequent buggy behavior. We would either have to write complex filter functions or just implement our own undo history which would be similarly complex. Each editable component already has a way to undo an action, so it was decided that this is a nice-to-have feature that could be prioritized during a future workcycle.
