### ISSUE TITLE
automated test to assert license/copyright statement at top of all files we create

### ISSUE THREAD

**Issue by ndushay** [LD4P/sinopia_editor#195]
Is there a way to do this as an automated check?

**Comment by justinlittman** [comment]
@michelleif Do we need to continue to add license/copyright since we have re-written the entire app?

**Comment by michelleif** [comment]
@justinlittman was this an issue of crediting the LC app or us stating that our app is open source?

**Comment by justinlittman** [comment]
This pre-dated me. @jermnelson what is your recollection?

**Comment by jermnelson** [comment]
When started with a hard fork of the BFE, we needed a way to copyright code being developed by Stanford using a Stanford approved open-source license so that it could co-exist with the LOC created code that was in public domain. This ticket was just a question by Naomi if we could automate this check.

**Comment by justinlittman** [comment]
Can re-open if this proves necessary.
