### ISSUE TITLE
figure out how Editor will use the resource template version property

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia_editor#2128]
**Describe the feature you'd like**
Add a version property to the resource template and profile validation when uploading.
 
**Give an example**
```
],
    "author": "LD4P",
    "date": "2020-04-03",
    "description": "Work, Instance, Item for Monographs, based on LC profile as of Aug-07-2019",
    "id": "ld4p:profile:bf2:Monograph",
    "title": "LD4P BIBFRAME 2.0 Monograph",
    "schema": "https://ld4p.github.io/sinopia/schemas/0.0.9/profile.json",
    "remark": "Updated",
    "version": "0.0.1"
  }
```

**Describe alternatives you've considered**

**Comment by gracianipicardo** [comment]
When trying to upload to Sinopia a profile with a "version" property on the profile metadata, Sinopia is currently giving the following error (screenshot):

<img width="508" alt="profile version error 2" src="https://user-images.githubusercontent.com/46054906/78409849-610b4f80-75d0-11ea-9da2-2450c2566225.PNG">

**Comment by gracianipicardo** [comment]
If the "version" property exists on the resource template metadata, then Sinopia gives the following error (screenshot):

<img width="510" alt="RT version error2" src="https://user-images.githubusercontent.com/46054906/78409948-b2b3da00-75d0-11ea-86b1-a052baaad0cd.PNG">

**Comment by michelleif** [comment]
see LD4P/sinopia_profile_editor#334

is Profile version relevant in the Editor?

Resource Template version property needs to be thought through: if you upload a new version of an existing Resource Template, what is expected behavior? don't overwrite the template (overwriting existing template is the current behavior). Show the resource template version in the Resource Templates list page? need to take into account the template version # when opening an existing resource? (see #2159)

**Comment by NancyL** [comment]
We still need a way to version templates. We now, at least, are able to update the creation date when cloning a template to create a new one, and we are beginning to use that as a form of versioning for updated templates, but we still need a more robust way to version that comes up with the rdf that specifically states what version a template is.

**Comment by justinlittman** [comment]
closing in favor of #2844
