### ISSUE TITLE
Validation

### ISSUE THREAD

**Issue by astridu** [LD4P/sinopia_editor#2164]
1. spellcheck, 
2. field-level validation that require specific inputs
3. check for blank nodes

**Comment by astridu** [comment]
![image](https://user-images.githubusercontent.com/42216982/82007799-07ab2d00-9620-11ea-99c4-afdac1d5fe4f.png)

**Comment by michelleif** [comment]
1) what needs to be spellchecked? all literals? might be counterproductive since there will be names, other uncommon words
2) validation is covered by https://github.com/LD4P/sinopia_editor/issues/2727
3) check for blank nodes where, and do what with them? don't we already know where there will be blank nodes, based on the template configuration?

**Comment by michelleif** [comment]
closing this as #2 is already covered by another ticket and #1 and #3 we are not pursuing
