### ISSUE TITLE
Improved relvancy ranking

### ISSUE THREAD

**Issue by astridu** [LD4P/sinopia_editor#2169]
Users can't find what they're looking for in Sinopia. The advanced search may help this, but understanding or modifying the relevancy ranking could help as well.

**Comment by jcoyne** [comment]
Searchworks has a suite of relevancy tests. Maybe we can have something similar?  Therefore when they change the ranking algorithm they can see which use cases will be impacted.  

For example one test is: When I search for "Nature" the journal "Nature" should be in the top 10 results. 

Can someone create a set of rules like that? So that we know the relevancy is good?

**Comment by justinlittman** [comment]
@astridu As we have multiple types of searches that query different sources can you clarify which are problematic?

**Comment by michelleif** [comment]
closing because not sure specifically what is not working. if we have specific examples of Sinopia search results where order by relevance doesn't make sense, please open new ticket
