### ISSUE TITLE
Fix the tabbing

### ISSUE THREAD

**Issue by astridu** [LD4P/sinopia_editor#2173]
The tabbing needs some refinement both for usability and accessibility.

**Comment by jermnelson** [comment]
@astridu Just to confirm; this ticket is referring to the tabs that are created when more than one resource template is loaded and not the navigation tabs at the top?
![Screen Shot 2020-05-07 at 9 05 53 AM](https://user-images.githubusercontent.com/71847/81311338-8281b000-9042-11ea-9196-09d491b75ed6.png)

**Comment by astridu** [comment]
This is wrt the interaction of tabbing (using the tab key to navigate) to the different sections, not the visual design of the tabs. Apologies for the confusion. I'll add more details soon.

**Comment by jimfhahn** [comment]
I have noticed that catalogers are accustomed to using form based layout for input of data. Most screens they use for cataloging support tabbing over to fields because the form is not broken up into cards. This might be too big of a change, but I think doing something like "class="col-lg-6 col-xl-12" for the cards -- making it look more like what catalogers are accustomed to may help supporting navigation in the page, possibly.

<img width="1252" alt="Screen Shot 2020-05-12 at 9 05 05 AM" src="https://user-images.githubusercontent.com/1310509/81702089-775ac580-9430-11ea-8f77-cee153193bec.png">
