### ISSUE TITLE
wrong tabs closing

### ISSUE THREAD

**Issue by gdegroat** [LD4P/sinopia_editor#2183]
There was a bug reported a  couple months ago and then corrected, where if there were multiple tabs, you'd close a record and assume that the record you were looking at (the highlighted tab) would close, but one of the other tabs would close instead.  So if you aren't careful you can close an unsaved record (since they are back to saying changes are unsaved again). 
I'm in production, using Firefox on a Windows machine.  I tried to close aw ork record but one of the administrative  metadata records closed instead.

**Comment by gdegroat** [comment]
Sorry, it was actually the instance record that closed when i closed the work.  I'm using the monograph unnested templates.

**Comment by gdegroat** [comment]
And in attempting to close the work it, it closed all other tabs one by one until it's the only tab left.

**Comment by michelleif** [comment]
Hi Greta, is this with using the "Close" button or using the little "x" on the tab?

**Comment by gdegroat** [comment]
Using the close button.  It's related to the "save and close" thing when it tells you you have unsaved changes.  THen you go ahead and click close and it closes the wrong one.  I haven't tried the x.

thanks
greta
________________________________

**Comment by gdegroat** [comment]
I used the close button, which i would assume would work on the 
highlighted tab.  I see that the x is available only on the 
non-highlighted tabs.

thanks

greta

**Comment by michelleif** [comment]
I'm trying to reproduce this but can't. Is it still happening after yesterday's new release? if so could you add a couple screenshots here?

**Comment by gdegroat** [comment]
![image](https://user-images.githubusercontent.com/44270367/81721298-86dc0d80-9434-11ea-96ec-6489bc1cc24d.png)
![image](https://user-images.githubusercontent.com/44270367/81721359-9b200a80-9434-11ea-9176-72d29723d71e.png)
![image](https://user-images.githubusercontent.com/44270367/81721418-affc9e00-9434-11ea-83ae-004204445817.png)

Interesting, i opened some and then closed, and i didn't have the problem.  Then i tried making a change and saving, which got me the "you have unsaved changes."  Then when i tried to close the one that i had saved, which was the first tab, instead it closed the last tab.

**Comment by michelleif** [comment]
to clarify, you made changes in Monograph Instance Un-Nested, and then saved, and then still got the "you have unsaved changes" message when trying to close the tab you had just saved? What version of Sinopia is your screen showing?

**Comment by gdegroat** [comment]
Yes, that was the one i made a small change in and saved and got the message.  Then i tried to close but the administrative metadata closed instead.  Sinopia version is v.2.0.21

**Comment by jermnelson** [comment]
Hi @gdegroat, thanks for the additional information and screen-shots. I believe I have replicated the problem locally and I have started work on a fix.

**Comment by michelleif** [comment]
This bug seems to be back.

1. open two resource templates. In this example on stage I opened **_PCC BF2 Work (Monograph)** and **_PCC BF2 Instance (Monograph)** and the active tab is Work
<img width="1168" alt="Screen Shot 2021-02-11 at 1 17 29 PM" src="https://user-images.githubusercontent.com/23069165/107699972-ab873f00-6c6b-11eb-9248-e541ef558a78.png">
2. add some data to the Work, and then attempt to close without saving
<img width="1172" alt="Screen Shot 2021-02-11 at 1 17 41 PM" src="https://user-images.githubusercontent.com/23069165/107700074-d376a280-6c6b-11eb-88de-da69b1644b74.png">
3. when you click Close in the warning screen, it closes the Instance tab instead of the active tab
<img width="1141" alt="Screen Shot 2021-02-11 at 1 17 51 PM" src="https://user-images.githubusercontent.com/23069165/107700138-eab59000-6c6b-11eb-9cec-7787323f01fc.png">

**Comment by michelleif** [comment]
see also #2057

**Comment by michelleif** [comment]
verified fix on DEV
