### ISSUE TITLE
add select all checkbox to filters on Search tab

### ISSUE THREAD

**Issue by astridu** [LD4P/sinopia_editor#2197]
Provide a 'select all' checkbox so you can select/unselect all institutions rather than having to check/uncheck each one of them.

**Comment by astridu** [comment]
![image](https://user-images.githubusercontent.com/42216982/81965902-93479e00-95cd-11ea-9b0a-5029ec6f253e.png)

**Comment by michelleif** [comment]
add "select all" box to all filters

**Comment by michelleif** [comment]
don't need "unselect all" because we have "only"

if user wants to "select all", they can redo the search at which point everything will be selected again.

so since there is workaround, closing this.

Michelle will add to Search documentation about how to use the "only" button and how to re-select all
