### ISSUE TITLE
default values don't appear in literal and lookup fields that are marked required

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#2371]
(This applies to what is currently on DEV)

For both literal and lookup fields that are **required**, the default value is not being displayed when the template is opened for entering data. Default value shows up as expected when field is **not required**

Examples:
required literal field with default, working as expected on PRD:
https://sinopia.io/editor/ld4p:RT:bf2:Monograph:Work:Un-nested
field: Content Type
default: text

compare on DEV:
https://development.sinopia.io/editor/ld4p:RT:bf2:Monograph:Work:Un-nested
default does not appear

required lookup field with default, working as expected on Stage:
https://stage.sinopia.io/editor/Sinopia:RT:Demo:SampleResourceFuller
field: Example 15

compare on DEV: 
https://development.sinopia.io/editor/Sinopia:RT:Demo:SampleResourceFuller

another example of template newly created on DEV with one literal field required and one literal field not required, both have defaults specified but the default doesn't show up in the required field:
https://development.sinopia.io/editor/michelle:test

**Comment by peetucket** [comment]
I did some investigation using the debugging  and redux tools console that here:

https://github.com/LD4P/sinopia_editor/blob/master/src/components/editor/property/InputLiteral.jsx#L67-L71

when `props.property.propertyTemplate.required` == true, `addedList` is empty because `props.property.valueKeys` is empty but
but in all cases `props.property.properyTemplate.defaults` is the correct array of two elements regardless of required attribute or not

when `props.property.propertyTemplate.required` == false, `addedList` has the expected default values

I have not figured out why this state is not getting set correctly when the field is required
