### ISSUE TITLE
Expand all sections on right panel in Editor and allow user to collapse / expand nested templates as desired

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia_editor#2541]
@astridu commented on [Mon Aug 24 2020](https://github.com/LD4P/sinopia/issues/300)

To complement the new left nav, update the right panel of editor to have all sections defaulted open.
- The entirety of the record should appear in the right panel. 
- User can scroll through the whole record on the right, or use the left nav links to go directly to a section.
- Update form fields 

![image.png](https://images.zenhubusercontent.com/5e13b724f29cd505881d7257/ff50734f-3bf4-4c6a-a1b1-a96847ac3617)

---

@justinlittman commented on [Tue Aug 25 2020](https://github.com/LD4P/sinopia/issues/300#issuecomment-680111085)

re "update the right panel of editor to have all sections defaulted open": How should defaults be handled?

---

@astridu commented on [Wed Aug 26 2020](https://github.com/LD4P/sinopia/issues/300#issuecomment-681346868)

I realize this is different from how we do things now technically, but from a UX perspective, it would be nice to have all the sections open, their defaults filled in, but it doesn't save until they click 'Save'. The checkmarks on the sections that have been filled in will tell them whether there is default content in there so they can decide to delete it if they wanted.

---

@justinlittman commented on [Thu Aug 27 2020](https://github.com/LD4P/sinopia/issues/300#issuecomment-681879595)

OK. That's totally do-able. Is this ticket intended solely for functionality changes or for also visual changes (e.g., the style of inputs)?

---

@astridu commented on [Fri Aug 28 2020](https://github.com/LD4P/sinopia/issues/300#issuecomment-683206055)

If it's easier, I can create another ticket for visual changes. Does that help?

---

@justinlittman commented on [Mon Aug 31 2020](https://github.com/LD4P/sinopia/issues/300#issuecomment-683805944)

Yes, it does help. I'd recommend a discussion with @jermnelson to discuss how proposed visual changes align with bootstrap.

---

@jermnelson commented on [Mon Aug 31 2020](https://github.com/LD4P/sinopia/issues/300#issuecomment-683839526)

@astridu, yes a separate ticket for visual changes in the right panel would be helpful so we can break down the UI changes into more discrete  "chunks". I started one ticket that would be belong with this ticket 2401 for change the label for input fields: https://github.com/LD4P/sinopia_editor/issues/2401

---

@michelleif commented on [Fri Sep 25 2020](https://github.com/LD4P/sinopia/issues/300#issuecomment-699164985)

This ticket is for the functionality change of having everything open. See Astrid comment Aug 26

**Comment by michelleif** [comment]
I'm reopening this because it appears we never did this for fields of type "nested resource". The fields are NOT being shown as open. We still have the old "+Add" button. 
Example: https://stage.sinopia.io/editor/pcc:bf2:Monograph:Work
The fields that are part of the Title nested resource are all closed. They should be open for entry, like the Form of Work field below Title.
<img width="865" alt="Screen Shot 2020-11-29 at 11 26 06 AM" src="https://user-images.githubusercontent.com/23069165/100551491-bf5b0180-3235-11eb-897f-9f159b1b153e.png">

All fields should be open. With a "V" icon to collapse them if user wants to. There shouldn't be +Add anywhere. (Only +Add another for repeatable nested resources). All fields should be like "Part Name" in this screen shot. "Preferred Title" and "Part Number" show how it would look if user closed.
<img width="863" alt="Screen Shot 2020-11-29 at 11 28 46 AM" src="https://user-images.githubusercontent.com/23069165/100551554-3abcb300-3236-11eb-8eaf-237e9ee327e5.png">

Related, for fields of type lookup or literal, when you use the trash can to erase everything in the field, the field ends up closed with a +Add. Instead the field should just be blank.

In the same template, the "Date of Work" field is a literal. It is shown open when the template is opened, as desired.
<img width="849" alt="Screen Shot 2020-11-29 at 11 33 46 AM" src="https://user-images.githubusercontent.com/23069165/100551639-cf271580-3236-11eb-92f2-4e2c933274ca.png">

If I add some text:
<img width="859" alt="Screen Shot 2020-11-29 at 11 34 55 AM" src="https://user-images.githubusercontent.com/23069165/100551656-ed8d1100-3236-11eb-9e45-b3f3776ff2a9.png">

and then use the "x" to remove the text I added:
<img width="837" alt="Screen Shot 2020-11-29 at 11 35 22 AM" src="https://user-images.githubusercontent.com/23069165/100551666-fed61d80-3236-11eb-917f-55aa0bad2c20.png">

the field is still open, as expected (and the date statement is removed from preview).

But if I use the trash can, I end up with this
<img width="837" alt="Screen Shot 2020-11-29 at 11 35 22 AM" src="https://user-images.githubusercontent.com/23069165/100551682-18776500-3237-11eb-896f-829f500030fc.png">

Instead I should end up with the field still open but blank.

Side note: Why do we have the trash can on simple (unnested) fields? is it just so you could easily delete everything in a field, when there are multiple values, instead of having to delete each one by one?

@astridu @NancyL was this your understanding of how things should work? (also cc @gdegroat who raised question about purpose of trash can)

**Comment by michelleif** [comment]
Closing in favor of ticket specifically about trash can issues https://github.com/LD4P/sinopia_editor/issues/2845

**Comment by michelleif** [comment]
actually, i want to reopen this. and revisit why we aren't showing nested resources as expanded. 
earlier discussions said if you expanded a nested template, you were adding statements to the resource and might not realize it.
but see for example: https://stage.sinopia.io/editor/pcc:bf2:Monograph:Work
if I click +Add Primary Contributor or +Add Contributor to expand those sections, no new statements are created.
(see also #2083)

**Comment by NancyL** [comment]
It used to be that if you didn't use the trash can, it wouldn't save because there was "an empty field" or something like that. Obviously things have changed because it doesn't do that now.
It is nice to be able to delete if you use "add another" unintentionally or in the wrong property. On the other hand, the "add another" and that trash bin are much too close together!

**Comment by justinlittman** [comment]
You _may_ be adding statements to the resource, e.g., if there are defaults.

**Comment by michelleif** [comment]
but we are already showing nested fields with default as expanded/open.

the only fields we are NOT expanding currently are nested templates with no defaults.

so if we expand those, is there a problem?

**Comment by justinlittman** [comment]
Expand templates with no defaults? I suspect that expanding some nested templates and not others would be confusing to users.

**Comment by michelleif** [comment]
isn't that what we do now? we expand those with defaults and don't expand those without defaults. that is confusing.

**Comment by NancyL** [comment]
I think people are looking for an expand all/collapse all function. This would include all fields, whether empty, already filled in by the cataloger or with a default. The navigation on the left shows what fields have data entered through the checkmark, so the need to keep these fields open just to show there is data there is redundant (though redundancy can be good...). On the other hand, many would like to collapse some of the larger nested templates once complete, to make the overall template shorter and easier to manoeuvre in .
