### ISSUE TITLE
Another problem with MARC conversion--literal not a URI again

### ISSUE THREAD

**Issue by gdegroat** [LD4P/sinopia_editor#2655]
I have one more MARC conversion error to report.  In Stage--using FIrefox.  This is another example of the same type of message.  In URI https://api.stage.sinopia.io/resource/87b800a6-1090-4f81-9aa0-938994899f4e  i get the following error message Server error: Error: Ooops, something went wrong: Not a URI: Ecology--Interactive multimedia

This record was newly input today.  As in the earlier one, it is a literal and i put it in that way (in the associated Work record)  In fact all of the subjects in that are literals but this is the only with a message.  I even deleted it and re-input the heading and saved, but i still got the same message.

![image](https://user-images.githubusercontent.com/44270367/95511793-cae42780-096c-11eb-9489-1725029881ed.png)

**Comment by justinlittman** [comment]
Looking at the Work (https://api.stage.sinopia.io/resource/df955b34-bd27-4226-834f-080c3580f037), I see multiple subjects that are literals:
```
<https://api.stage.sinopia.io/resource/df955b34-bd27-4226-834f-080c3580f037> <http://id.loc.gov/ontologies/bibframe/subject> "Nature--Effect of human beings on--Interactive multimedia" .
<https://api.stage.sinopia.io/resource/df955b34-bd27-4226-834f-080c3580f037> <http://id.loc.gov/ontologies/bibframe/subject> "Introduced organisms--Interactive multimedia" .
<https://api.stage.sinopia.io/resource/df955b34-bd27-4226-834f-080c3580f037> <http://id.loc.gov/ontologies/bibframe/subject> " Feral animals--Interactive multimedia" .
<https://api.stage.sinopia.io/resource/df955b34-bd27-4226-834f-080c3580f037> <http://id.loc.gov/ontologies/bibframe/subject> "Ecology--Interactive multimedia" .
```

Any one of these will result in the `Not a URI` error. The reason literals cannot be mapped for subjects is that there isn't enough information to determine which MARC field to put the literal into.

I'm going to change so that it will ignore literals rather than erroring.
