### ISSUE TITLE
for lookup fields, show which authorities are being searched (before search), and add a link to the external authority

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#2687]
We don't offer any clues to user about what authority they are searching, in lookup fields. They only see which authorities are being searched **after** running the search. 

(1) Let's somehow show which authorities are being searched. 

(2) Also, it would be helpful to provide a link to a page about the external authority, such as the external authorities own "home" page, so that users can get more information about the authority. In many cases, an external authority will also have more tailored search features than QA (for example with Getty's AAT there are a lot of features to support hierarchical browsing of the thesaurus). There are use cases where user wants to find a URI from the authority's own lookup page and copy it into Sinopia.

(see another new ticket we are making to request that QA supports entering of URIs as search term)

The link to the external authority could be a tooltip on the name of the authority in the QA lookup (but that doesn't solve problem 1 of those names not being visible **before** you search.

**Comment by gdegroat** [comment]
Also, there are searches for related items that search Sinopia rather than an external authority, and they look identical to the authority search, so that can be confusing to the user.  Particularly since we are accustomed to searching external authorities and databases for those very things.  So if it is going to be searching Sinopia instead it should show that, especially if you do end p showing which authority is being searched up front.

**Comment by michelleif** [comment]
this is done! _example_
![Screen Shot 2021-09-29 at 9.49.46 AM.png](https://images.zenhubusercontent.com/5d825bf74def500001d12e70/f05cf4de-4998-4862-b16f-f86e12182a41)
