### ISSUE TITLE
Search result display of URI with another URI appended

### ISSUE THREAD

**Issue by gdegroat** [LD4P/sinopia_editor#2706]
In stage, Firefox, i searched the URI  https://api.stage.sinopia.io/resource/b11ddee3-51ca-46bc-aec5-56554f39a9bc  for an instance and the search results displayed the URI with the URI  http://id.loc.gov/ontologies/bibframe/Electronic  appended.  See the screenshot.

The URI http://id.loc.gov/ontologies/bibframe/Electronic had come from the last field of the record, Subclass of instance, but it's not in there now.  Last week there was an error in the template and there were two occurences of the field Subclass of Instance in the template, both of which defaulted to Printed.  I changed one to http://id.loc.gov/ontologies/bibframe/Electronic and deleted the other.  Then Nancy corrected the template so there was only one occurence in the template.  That one has the default value Printed, so i didn't know where the one i had previously changed to http://id.loc.gov/ontologies/bibframe/Electronic went.  The first time i opened the template after the changed, it showed the second occurence of Printed as an usused triple but it's not there now.  I have made no changes to the record since the template changed, i just looked at it and closed without changes.    Anyway, it looks like the value that i had input in the record for that field last week can no longer be found by opening the record and looking at it but can be found in the search results screen, as shown in the screenshot.
![image](https://user-images.githubusercontent.com/44270367/98016056-5efdaf00-1db2-11eb-9a8f-7579d5cfcef4.png)

**Comment by gdegroat** [comment]
I am checking the two other instance records which i input when the form had the extra subclass of instance, an done is showing the stray URI in the search results, and the other isn't.

https://api.stage.sinopia.io/resource/b11ddee3-51ca-46bc-aec5-56554f39a9bc
 was another one where  i had changed one of the Subclass of Instance fields to Electronic (i probably attempted to delete the other, or at least to x out the default value)

However, https://api.stage.sinopia.io/resource/9b72126d-2de2-412e-9e22-e46b8b20b93e  was a print resource where i did not attempt to change the default value (can't remember if i tried to delete the stray one or not) and the search result in the Class column is still not correct--it shows 2 URIs, but should just show the URI for instance.  Weirdly, the Work record for that is also having this display, see the below screen--the top and bottom records are the work and instance records for this item, interspersed with some other items showing a normal looking URI in the class column.  
![image](https://user-images.githubusercontent.com/44270367/98020385-ccf8a500-1db7-11eb-9577-b8dc317547fe.png)

**Comment by michelleif** [comment]
investigating. is that the right screenshot?
it doesn't show https://api.stage.sinopia.io/resource/9b72126d-2de2-412e-9e22-e46b8b20b93e
also https://api.stage.sinopia.io/resource/b11ddee3-51ca-46bc-aec5-56554f39a9bc mentioned above was described in original ticket, is there an additional resource that is not as expected?

**Comment by michelleif** [comment]
in any case, the way these 2 templates are set up, there **are** 2 classes for the resource so the search results are as expected

For pcc:bf2:Monograph:Work, the template definition states that the class of the resource will be http://id.loc.gov/ontologies/bibframe/Work

and that template also has an additional field "Type of Work" which states that the resource also has class "Text"

if the only applicable value in "Type of Work" is "Text", the question is why not configure the template to have class "Text" instead of "Work"? 

in the instance template pcc:bf2:Monograph:Instance, I see that you want the cataloger to be able to say whether it's Electronic, Manuscript, Tactile, or Print. And maybe there isn't enough variation among those types of Instances to warrant a separate template for each?

In https://api.stage.sinopia.io/resource/b11ddee3-51ca-46bc-aec5-56554f39a9bc I'm guessing what happened is that you added the "Electronic" statement (which still appears in the JSON and in the search results as you noticed), then the template changed, and the field where "Electronic" would go now has a default value. It might also be that because the template itself has a class, as well a field for class, Sinopia doesn't know where to try to put the "Electronic" value.

I would do this to try to fix:
edit the template itself to make the "Subclass of Instance" field repeatable, then see if Electronic appears, delete it, and fix the template to make the field nonrepeatable again.

@justinlittman this is pcc:bf2:Monograph:Instance on Stage: In general Sinopia doesn't allow two fields with the same property in the same template so it's interesting that Sinopia allows this (the "class" defined by the template itself and the "class" added in the "Subclass of Instance" field) but that might explain why there are unexpected results.

**Comment by gdegroat** [comment]
I didn't include a screenshot for https://api.stage.sinopia.io/resource/9b72126d-2de2-412e-9e22-e46b8b20b93e.   So, if Subclass of Instance is another type that's going to display as well as whether something is a work/instance/admin/item, that's fine, as long as it's expected behavior.  Since Subclass of Instance is a new field, it did't display in earlier records, which is what i was comparing the display to.  Thanks for the explanation!  And i'm not a template editor and these are just Stage records so i don't think it'll hurt anything if i leave the records with the errors, since it's unlikely to happen again.

**Comment by justinlittman** [comment]
OK. I'm going to close this ticket. Feel free to re-open if you feel necessary.
