### ISSUE TITLE
Create New button on PCC_BF2_Work_Monograph template does not work

### ISSUE THREAD

**Issue by dezel002** [LD4P/sinopia_editor#2716]
The Create New button which appears with the In series RT on PCC_BF2_Work_Monograph template does not function as intended. When I click on the button, I'm prompted to select a template from a drop-down list. In most cases, a Serial Work template would be the logical choice (either the LD4P Serial Work or PCC Serial Work). No matter what I select, Sinopia instead sends me to a blank Monograph Work template, and the monograph work I was working on is gone. There is an error message that flashes between the time of selecting from the menu and the blank Work template coming up, but it goes by too fast to read.

I am using Sinopia Stage in Firefox 82.0.3.

This is possibly related to issue #2712 .

**Comment by michelleif** [comment]
The list of templates offered under Create New is as expected (see below) but you're right, it's not opening the template that you _do_ select from the Create New dropdown.

As expected:
"Create New" shows you a list of any resource template of type Work. (Since the lookup is to Sinopia Works, Sinopia assumes you want to create a new Work. Sinopia has no idea what kind of Work.)

Bug:
When you do select something from the dropdown, the selected template should open in a new tab, leaving the one you were working on alone.

We need to fix this bug.

As an enhancement, we could consider letting the template creator define what the button does. For example, in the "In Series" field, one would configure the template so that "Create New" did not give the cataloger a choice but instead opened a new "Serial Work" template. This could be really useful for Contributor too, to open a new template for a new Agent.

**Comment by michelleif** [comment]
I'm not seeing a Create New button anymore. Here's my test template with a field that's a lookup to Sinopia Works.
https://stage.sinopia.io/editor/testing123:1

**Comment by michelleif** [comment]
in this template on stage https://stage.sinopia.io/editor/pcc:bf2:Monograph:Work the "in series" field has a create new button and it seems to be working properly now.

but the "has BIBFRAME instance" field does **not** have a Create New button, even though it is a lookup to "Sinopia BIBFRAME Instances". Shouldn't that produce a Create New button with a list of templates of class Instance?

also, the test template above https://stage.sinopia.io/editor/testing123:1 has 2 fields both lookups to "Sinopia BIBFRAME work resources" but it is not showing a Create New button either.
