### ISSUE TITLE
root template: show context for authorities in  "Lookup attributes" (or add tooltip to QA documentation)

### ISSUE THREAD

**Issue by kirkhess** [LD4P/sinopia_editor#2729]
In the values section, the new display with a list of sources from QA makes this somewhat inaccurate since the label says "uri" but you just have a label for the uri; you can't add uris or see the uri being used.

The control could be changed to display URIs instead of the labels but I think it would be better to just change the label 'uri' to something more descriptive (Lookup/Source/Link), change the list so it is slightly more user friendly and add a hover option to show details for each source w/a hyperlink.

**Comment by michelleif** [comment]
ticket originally written for Profile Editor

revised requirement:
when creating a template, under "Lookup attributes" you get a menu of authorities. would be nice to have some context on those so that the template creator knows which authorities they're choosing. failing that, we could add a tooltip (to the root template) that links out to QA documentation describing each lookup.

**Comment by justinlittman** [comment]
Additional information about authorities is provided in existing help text, so closing.
