### ISSUE TITLE
System driven metadata (PCC wish list no. 

### ISSUE THREAD

**Issue by NancyL** [LD4P/sinopia_editor#2788]
This overlaps with a number of other issues, referenced below, but is more comprehensive

The following properties in the Administrative Metadata should be machined-generated.
This is not yet possible in Sinopia
○ bf:creationDate (timestamp)
○ bf:modificationDate (timestamp)
○ bf:generationProcess (Description of program or process used to generate the
description by application of a particular machine transformation)--e.g., a MARC 883 field (though I don't know if anyone uses it yet; I need to check)
○ bf:procInfo (Processing information for the BIBFRAME description (e.g. when
updated))

similar/related issues: #1903 , #2206

**Comment by michelleif** [comment]
closing in favor of #2899 which asks for system-generated values in generic terms, so that it can be used with any template and any property. #2899 covers creation and change dates.

it does not cover "generation process". if it turns out that is needed, we will need a separate ticket that explains how to determine the value
