### ISSUE TITLE
validate data in literal fields against datatype or regex specified in template

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#2890]
if a literal field has a datatype (see #2889) or a regex (see #2907) specified, validate that entered data conforms to the datatype or regex

if it doesn't, show error message "Not a valid [datatype]" or "Entered data must match [regex]" (or whatever wording makes most sense)

**Comment by justinlittman** [comment]
The datatype and regex can be added to a template by template author. See #3284.

This ticket will require:
* Adding `regex` and `datatype` to subject template when loading template to state in `TemplateBuilder`. (Don't forget to add these new attributes to state documentation in README as well.)
* Adding validation in `resourcesHelpers.js`. See https://github.com/LD4P/sinopia_editor/blob/main/src/reducers/resourceHelpers.js#L180. I'd suggest that this method is too large and should be refactored into smaller methods; possibly validation should be moved into its own file, instead of `resourceHelpers.js`.

**Comment by ndushay** [comment]
- what about invalid regex?
    - are we expecting slashes and stuff
- what about invalid datatype?
    - how do we decide if the literal is edtf or integer or dateTime, etc?    (is there a library we can use?)

We currently validate templates on ingest;  we probably want to validate regex on ingest as well (ingest == load ...)

**Comment by ndushay** [comment]
What remains:
- [ ] add these new attributes to state documentation in README
- [ ] document regex for users (where/how?)
- [ ] document integer, dateTime, dateTimeStamp for users (where/how?)
- [ ] split out edtf into separate issue, possibly including config changes already made migrating to a diff branch.  Include possible npm packages already located.
- [ ] refactor resourceHelper

**Comment by michelleif** [comment]
-re user documentation, there are lots of existing regex documentation resources so we should not need to write, in #2892 i suggested one; also per #2892 we will link to definition of those types for user, so no need to document

**Comment by ndushay** [comment]
@michelleif we will need to figure out if backslash in regex need more than a single additional backslash to work (e.g. "^\\d+$" becomes /^\d+$/ in our code), and want to encourage people to use the "^" and "$" anchors to avoid unintended matches, perhaps.

**Comment by NancyL** [comment]
Jeanette mentioned this: https://www.youtube.com/watch?v=0khvMJGIuzA&list=PLrHRsJ91nVFQEr_dPopYTAXUWYTKkcFpj&index=8 to me. It's from the MARCedit series, but I think it is pretty general.
