### ISSUE TITLE
distinguish between +Add another at nested resource vs field level

### ISSUE THREAD

**Issue by gdegroat** [LD4P/sinopia_editor#3160]
This was reported to the PCC Sinopia Cataloging Affinity Group as a possible bug, so i asked Michelle about it.  She says that the intent is the new way of adding multiple values in a repeating field (before, you typed one value, hit enter, it went below the box, and you could then type another).

However, in the affinity group we were confused by this since it's the same wording as the "add another" command at the node level.  And since we had been stressing that for things like contributors you always need to add another at the node level (even though it was possible to add another by hitting enter), we found it confusing to find this at the field level.  We thought it either was an intentional bug, or perhaps to add multiple labels and URIs for the same entity.  So both of our guesses were wrong.

This group already knew that they needed to create a new node for a new entity, but less experienced users would likely assume it was for multiple contributors (of course the primary says only 1, but it could be easily confused on the other contributors).  

So there needs to be some differentiation in text i think between the two commands.  Their looks are slightly different, but since the text is the same it's not clear what the new one is supposed to be for. Or even why it is needed on fields where you do need to start a new node for another entity.

I entered an example on https://api.stage.sinopia.io/resource/c96d8b55-e0ac-48a5-9a9b-b0684758c99e to see how it looks in the RDF and it does look like it's in the same node (i think it's :b8)

thanks
greta

**Comment by NancyL** [comment]
I see what Greta is saying here. 

When there is a blank node, if we want to "add another", we are talking about the blank node. For example, in bf:Contribution, to keep all the properties in the blank node together (bf:agent, bf:role), we need to repeat the entire blank node, rather than simply "add another" bf:agent. If I "add another" agent as it so prominently suggests I do, I will get a blank node that contains 2 agents and 2 roles, the roles not in any way associated with the right agent.

This problem is accentuated by the current UX, in which the "add another" for the bnode is in tiny letters off to the side, while the field "add another" is larger and in your face. This is indeed a problem in user design.

We cannot remove the repeatability of something at the field level in a bnode if the primary property (in this case, bf:contribution) is repeatable. This has been a known problem for a while, but thought of as lower priority. Unfortunately, this current view makes it a much higher priority.

![image](https://user-images.githubusercontent.com/5078198/137014771-47be91e5-79d5-4b09-b244-9395e164bba4.png)

**Comment by michelleif** [comment]
if you nest a template and make it repeatable, yes, the entire chunk can be repeated. if there's a non-repeatable field in the nested template, it doesn't become repeatable. it is still only allowed once per "chunk".

@NancyL can you remind of the place where you are wanting to have two fields with the same property and are not able to do that now? so we can explore solutions?

**Comment by justinlittman** [comment]
If you wanted to, we could also do the same for the other "Add another" button, e.g., "Add another Name of Person".
