### ISSUE TITLE
Set defaults for Nested Resource

### ISSUE THREAD

**Issue by kevkishi** [LD4P/sinopia_editor#3234]
I'm not sure how this would work, but it would be very cool to be able to set a default value for a Nested Resource, especially those that are suppressible lookups.

For example, see template: pcc:bf2:PlayingSpeed
Playing Speed requires its own template because we need to set the rdf:type to bf:PlayingSpeed, which is a subclass of bf:SoundCharacteristic.
We use the same property bf:soundCharacteristic for all the Sound Characteristic subclasses, so the subClass is very important to include in our RDF.
Other bf:SoundCharacteristic subproperties would also require similiar templates.
If I am creating a template to catalog a specific type of media format (e.g. CD, LP), then the bf:soundCharacteristic properties would be the same for many of the Instances.
It would be nice to be able to set the bf:PlayingSpeed to "33 1/3 rpm" on a template for LPs.

**Describe alternatives you've considered**
The only alternative I can conceive is to create a separate Nested Resource template for each value (https://id.loc.gov/vocabulary/mplayspeed.html)
template 1 for bf:PlayingSpeed = 33 1/3 rpm
template 2 for bf:PlayingSpeed = 78 rpm
template 3 for bf:PlayingSpeed = 1.4 m/s
template 4 for bf:PlayingSpeed = 7 1/2 ips
etc.

Thanks so much.
Kevin

**Comment by michelleif** [comment]
Sorry I didn't answer this before but Nancy's suggestion to have the default set by an individual inspired another suggestion:

You could create your Sound Recording template with Sound Characteristic subtemplate, open the Sound Recording template for cataloging, add all default values that are appropriate say for an LP, and then save this "partially cataloged record".

Then, instruct catalogers who are cataloged an LP to **copy** your "partially cataloged record" as a way to start cataloging an LP. That way the default values will be there.

Also, you could save this "partially cataloged record" into a Group with a limited set of members so that no one can mess with your defaults.

And, if you give this Sound Recording template an rdfs label field and fill it in with something descriptive like "Default record for LPs", catalogers could find the "Default record" in Search.

Related suggestion:
I'm not sure if you are planning to create a subtemplate for every bf:SoundCharacteristic subclass? but if so, another way to approach it would be to create a generic bf:SoundCharacteristic template that has two fields: (1) is the field where the cataloger will type the value, like `78 rpm`. (2) is the field where the cataloger will say what type (subclass) of bf:SoundCharacteristic this value is.

Then, in your Sound Recording template, you nest the generic Sound Characteristic template and make it repeatable. Cataloger creates however many repetitions needed for each Sound Characteristic they need to catalog. Here's an example (on DEV) of an Instance with a nested repeatable Sound Characteristic template (there are no other fields): https://development.sinopia.io/editor/rt5

**Comment by NancyL** [comment]
Michelle, that is an interesting idea. We will need to try it out.
@kevkishi we need to talk about pcc templates vs MLA templates vs Stanford templates & some of the conceptualizing between them

**Comment by michelleif** [comment]
Closing this since there's a workaround
