### ISSUE TITLE
Change or remove sticky header

### ISSUE THREAD

**Issue by justinlittman** [LD4P/sinopia_editor#3310]
The current sticky header in the Editor is causing problems in which things are stuck below it. For example:

![image](https://user-images.githubusercontent.com/588335/140748784-39435f36-598e-4c5c-a21f-ac67ef154f7c.png)

Please try to change the sticky header so that it works like a Github ticket (only becomes sticky when scrolled to top) or remove the sticky feature.

**Comment by justinlittman** [comment]
refs #3305

**Comment by jcoyne** [comment]
@justinlittman how do I navigate to a place I can see this problem?

**Comment by justinlittman** [comment]
There are at least 3 problems.
1. Open a resource and click "Actions". See above.
2. Left nav tabs are partially obscured as described in #3305.
3. Sometimes when automatic scrolling is performed, the input is scrolled to underneath the sticky header. Open https://development.sinopia.io/editor/ld4p:RT:bf2:Monograph:Work:Un-nested and click "Date of Work" in left nav. The title for "Date of Work" is under the sticky header. (I feel like there are worse cases of things scrolling under the sticky header, but I don't have precise instructions.)

**Comment by jcoyne** [comment]
Okay, so the nav-items dropwdown is diving below the sticky row. We just need to adjust it's z-index.

**Comment by peetucket** [comment]
I looked into the scrolling issue (item #3 on the list above).  As noted by Justin, this is not due to z-index or the sticky row, it's just that the field being scrolled to is what is at the top.  We use `elem.scrollIntoView` here: https://github.com/LD4P/sinopia_editor/blob/main/src/hooks/useNavLink.js#L40 

And that method doesn't support offsets: https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView

I found some suggestions, and the best one that worked for me was to do a computation of the scroll position and just go there: https://stackoverflow.com/questions/24665602/scrollintoview-scrolls-just-too-far

See the change: https://github.com/LD4P/sinopia_editor/pull/3311/files#diff-45536682df11805e9e876ba014f35400190294297ad306f8cd5bf005808c1034R40-R43

**Comment by justinlittman** [comment]
See also #3314

**Comment by justinlittman** [comment]
At this point, let's just remove the sticky header.

**Comment by peetucket** [comment]
I think the z-index change to CSS in #3311 will fix these cases of the drop-down menus being obscured.  The scrolling issue is (mostly) dealt with in the same PR too (though there may be still be edge cases with long headers, it's not fatal if the scroll isn't perfect).
