### ISSUE TITLE
possible actions on templates: make consistent among different areas of app

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#3324]
Action required for this ticket: Add view action in `ResourceTemplateRow` (between new/create and edit). Make sure the additional icon does not break the table layout.

![image](https://user-images.githubusercontent.com/588335/145258705-462950e3-2762-403a-9ff7-01fa1bfeef4d.png)

-------------------------------------
we have four actions you can perform on any resource (including templates), by using the icon buttons:

view
copy
edit
create

however we are inconsistent in where we offer these icons for use on templates:

on the Resource Templates tab, and on Dashboard / Recent templates we don't offer view:
![Screen Shot 2021-11-12 at 10.31.57 AM.png](https://images.zenhubusercontent.com/5d825bf74def500001d12e70/f3c397ae-881b-4d6d-8772-ca1df161e1a1)

![Screen Shot 2021-11-12 at 10.33.11 AM.png](https://images.zenhubusercontent.com/5d825bf74def500001d12e70/928a1ebf-bc5c-4672-b22b-3d50141ac708)

on Dashboard / Recent **resources**, if a template is in the list of recent resources, we **do** offer view, but we don't offer create:
![Screen Shot 2021-11-12 at 10.34.14 AM.png](https://images.zenhubusercontent.com/5d825bf74def500001d12e70/5c25e4cc-fad2-48bf-afb1-71ba83083700)

@astridu can you advise?
should we offer all 4 icons whenever a template is listed in Dashboard and on the Resource Templates tab? to make things consistent?

**Comment by astridu** [comment]
I agree that we should offer all 4 icons for templates as well.

**Comment by justinlittman** [comment]
Why would you view a template? That doesn't seem very helpful for a template.

**Comment by michelleif** [comment]
if it's not helpful then we shouldn't offer it on templates in Dashboard / Recent resources, which we do now

**Comment by justinlittman** [comment]
It is not offered in the templates section; only in the resources section. If you create a new resource using a template, the template does not appear in the resources section. If you edit a template, the template appears in the resources section.

On the one hand, that seems consistent; on the other hand, you could make the case that when you edit a template, the template should not appear in the resources section. Has there been any user feedback to suggest that more special handling for templates is warranted?

**Comment by NancyL** [comment]
I would want to look at a template to consider whether it is appropriate for the cataloging the material I have or whether I should copy it and create a new one from it, rather than having to go into edit mode and back out. Also nice to see who "owns" it.

So I'm getting a little confused by the last point. Right now in the dashboard, we have both "Recent templates" and "Recent resources" and yes, there are templates in the "Recent resources" which are not the same as in "Recent templates". And those templates in "Recent resources" can be viewed; if those can be why not the ones under templates? It is inconsistent. And I didn't actually edit those templates; I just opened them up.

**Comment by michelleif** [comment]
yes let's do this and offer all 4 icons in all places (depending on user's permissions of course)
