### ISSUE TITLE
Cannot nest two different templates that are the same Class

### ISSUE THREAD

**Issue by kevkishi** [LD4P/sinopia_editor#3355]
Hi.
I don't know if this should be considered a bug fix or a feature request (or maybe something that shouldn't be done for logical reasons)

**Describe the bug**
See: pcc:bf2:AudioRecording:Instance:SingleTemplate
At the very bottom of this template there is bf:contribution property, for which I would like to nest two different bf:Contribution templates:
pcc:bf2:Contribution:Performer:Music
pcc:bf2:Contribution:Music
![Screenshot 2021-11-18 094503](https://user-images.githubusercontent.com/57068255/142468730-a308907a-bb2e-4cb9-9099-cd2b34e5e32d.jpg)

When I try to create a new resource with this template, I get an error:
"The following resource templates references for http://id.loc.gov/ontologies/bibframe/contribution have the same class (http://id.loc.gov/ontologies/bibframe/Contribution), but must be unique: pcc:bf2:Contribution:Performer:Music, pcc:bf2:Contribution:Music"

I understand that in many cases one wouldn't want to nest different templates that create the same Class, so I get this limitation. But in this specific case, although both templates create bf:Contribution resources, the templates have different properties from one another. The performer template includes several additional properties that ONLY apply to music performers.

- What is the impact on your work? (can't work / work stoppage; workaround exists; minor issue)
I can't continue working on this template as I conceived it.

I could create a less-than-ideal resource template to share with PCC. I would simply remove one of the bf:Contribution templates from this property, and only nesting the Performer template. I would have to relabel more generally and give specific user guidance to IGNORE the music-performer-only properties when describing non-performer Contributions.

Alternatively, we could create a subclass for bf:Contribution, maybe PMO:MusicPerformerContribution
But we would need to have discussion before changing the ontology

- What environment are you in? (stage or production)
Stage

- What OS and browser are you using? (Mac/Windows; Safari, Firefox, etc.)
Windows 10, Chrome

- If you're cataloging, what Resource Template were you using (name or ID)

**Please include a screenshot**
(Mac: shift-command-4; Windows: ; then drag the image file into the issue)

**Comment by michelleif** [comment]
I think your solution of including only the Performer contribution template is a good one. I'm not sure if you are expanding it, but right now it only has 2 "extra" fields compared to the non-performer Contribution. Since those fields are not required, would you need to explain to ignore them? You could add a Remark (tooltip) to provide more information if necessary.

The reason that Sinopia doesn't allow two nested templates using the same property and the same class is that if you created some data, when you go to open it back up, Sinopia wouldn't know which field to put the data into. You can see a longer explanation and examples here:  https://github.com/LD4P/sinopia/wiki/Why-Sinopia-doesn't-allow-repeated-propertyURIs-in-a-single-Resource-Template

@justinlittman might have other ideas about workarounds or a fix.

**Comment by kevkishi** [comment]
Understood.
Thanks for the explanation
