### ISSUE TITLE
Date literal default

### ISSUE THREAD

**Issue by justinlittman** [LD4P/sinopia_editor#3358]
Like #3357, except will allow defaulting to a date (`yyyy-mm-dd`).

**Comment by NancyL** [comment]
See that you are working on this, so some issues with admin metadata that came to me in the middle of the night:
This only has to with date, not user ID. We discussed how and when to add a date, first to the creationDate & second to the changeDate and also relating actual users to the changeDate. We agreed that we would need to repeat the template to get the relationship, but I know I also said that perhaps I could create two adminmetadata templates--one that only contained a creationDate & one that only contained a changeDate. I realize now that this is not possible, since I can't point to 2 separate nested templates that are for the same class. At least, I believe not!
So that still leaves date as something of an issue and how to know which field to fill. I'm wondering, if instead of an autofill on save, a cataloger might be able to tell the system which field to fill, by clicking on a checkbox for the field to fill, perhaps, or maybe even a pull-down with choices of "none" and "today" which is how Symphony does it. Don't know if either is possible, but just throwing out ideas

**Comment by justinlittman** [comment]
For the planned implementation, a literal property can be set to have a "date default". When this is set, the default will be the date (just like other default values specified in the template). The cataloger will be able to change and/or delete the date. (In other words, it will autofill on opening, not on save.)
