### ISSUE TITLE
Provide customizable label creation for chooseable property lists

### ISSUE THREAD

**Issue by NancyL** [LD4P/sinopia_editor#3552]
**Describe the feature you'd like**
We now have the ability for catalogers to choose a property through a dropdown menu (which we love!). However, the template only allows you to provide a URI for the property, not a label. This is a major drawback. Generally, we don't want to force catalogers to read and interpret URIs as they catalog. Also, in many cases the URI is not human-readable (example follows) or we want to provide a label that conforms with the cataloging standard rather than BIBFRAME.
**Give an example**
A screenshot below shows what it looks like now. Having it with the format "Label (URI in parentheses)" would be good.
Examples of what we like it to look like:

- Date cataloged (http://id.loc.gov/ontologies/bibframe/creationDate)
- Abridgement of (http://rdaregistry.info/Elements/u/P60359)

**Describe alternatives you've considered**
![image](https://user-images.githubusercontent.com/5078198/174388671-a4147588-8bb6-49ba-9ede-bd59699112a7.png)

**Comment by CECSpecialistI** [comment]
I also love the dropdown menu for property selection! Using labels instead of or in addition to URI's is also important for ontologies outside of BIBFRAME, many of which do not have URI's that are meaningful to humans (for example, RDA's property for "creator person of work": http://rdaregistry.info/Elements/w/P10437). In the context of RDA resource templates, catalogers will not be able to navigate the lists in a reasonable amount of time without human-readable labels.
