### ISSUE TITLE
(Safari, Firefox) Browser not refreshing list of Resource Templates

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia_editor#507]
Safari:  When uploading a Profile containing one or more Resource Templates, the expected success message is being returned but the list of available Resource Templates is not being update in the display.

Firefox:  When uploading a profile, the success message is not returned the first time;  you have to do it twice.

~~Blocks #506~~

**Comment by michelleif** [comment]
and in Chrome (based on testing today in DEV), when you upload a new Resource Template, you get the message in blue showing it was uploaded, but it doesn't show up in the list below. If you refresh the browser window, then it does show up.

**Comment by ndushay** [comment]
Running code locally (may) work, but doesn't work in deployed environment?

**Comment by michelleif** [comment]
here are 3 profiles for testing this. they all have one Resource Template with one Property Template. But each one's Resource Template has a unique ID and label, so that you can test this 3 times (Firefox, Chrome, Safari. IE? worry about that later)

when you upload one of these Profiles you should get the message in blue that the contained RT has been uploaded, and the contained RT should appear in the list below, as follows (replace 1 with 2 and 3 as needed)

Profile: testing refresh of new profiles take 1.json.txt
contained RT ID (should appear in ID column):testing_refresh_new_RT1
contained RT Resource Label (should appear in Template Name column): can you hear me now? take 1

[testing refresh of new profiles take 3.json.txt](https://github.com/LD4P/sinopia_editor/files/3175041/testing.refresh.of.new.profiles.take.3.json.txt)
[testing refresh of new profiles take 2.json.txt](https://github.com/LD4P/sinopia_editor/files/3175042/testing.refresh.of.new.profiles.take.2.json.txt)
[testing refresh of new profiles take 1.json.txt](https://github.com/LD4P/sinopia_editor/files/3175043/testing.refresh.of.new.profiles.take.1.json.txt)

**Comment by michelleif** [comment]
I tested this on DEV and  it is not working for me. I am using some profiles that contain only 1 Resource Template, and those Resource Templates are new to Trellis

Safari: upload RT friday2, get blue confirm message but RT doesn't appear in list
<img width="1123" alt="SafariFriday2" src="https://user-images.githubusercontent.com/23069165/57962345-89139680-78ca-11e9-89bf-7c4594e443b2.png">

Firefox: upload RT friday5, get blue confirm message but RT doesn't appear in list
but friday2 (uploaded over in Safari) does appear
<img width="1241" alt="FirefoxFriday5" src="https://user-images.githubusercontent.com/23069165/57962350-929cfe80-78ca-11e9-9f5d-6f998372a080.png">

Chrome: upload RT friday6, get blue confirm message but RT doesn't appear in list
friday2 and friday5 don't appear either
<img width="1198" alt="ChromeFriday6" src="https://user-images.githubusercontent.com/23069165/57962375-c24c0680-78ca-11e9-9526-c34f00814099.png">

I'm not going to include those specific profiles here because if you try them again, then you're testing uploading an existing profile, but here's friday7 which is the same as the ones I used for testing except for the name and label:
[friday7.json.txt](https://github.com/LD4P/sinopia_editor/files/3193467/friday7.json.txt)
