### ISSUE TITLE
Search Tab -  Simple Search and Results Table

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia_editor#583]
Conferred with @astridu regarding the UI for the **Browse** tab in the Editor. Here is an earlier design that we can use (with red x on parts of the design we are no longer using):

![Screen Shot 2019-05-29 at 3 56 19 PM](https://user-images.githubusercontent.com/71847/58597135-83537480-822b-11e9-8f13-cb10d255d415.png)

This would have a single input field to do a keyword search in Sinopia's Elasticsearch index and return a list of entities that are ordered by relevancy.

**Comment by mjgiarlo** [comment]
Clarifying this issue:

1. We will re-label this tab "Search" instead of "Browse"
2. When first clicking over to the Search tab, it should render *only* the search bar and, when a user enters a search string with results, *then* render the table of results below.

Screenshots:

![search_box](https://user-images.githubusercontent.com/131982/59790397-b87c4100-9284-11e9-837a-db42cdce70d1.png)
![search_results](https://user-images.githubusercontent.com/131982/59790406-bc0fc800-9284-11e9-8ebb-918ec2454230.png)
