### ISSUE TITLE
Language tag should be transformed to RDF

### ISSUE THREAD

**Issue by jcoyne** [LD4P/sinopia_editor#666]
Currently, when "preview" is clicked, the language tag isn't displayed.

**Comment by justinlittman** [comment]
Languages are selected from https://id.loc.gov/vocabulary/languages.json. For example, here's English:
```
{
@id: "http://id.loc.gov/vocabulary/languages/eng",
@type: [
"http://www.loc.gov/mads/rdf/v1#Authority",
"http://www.loc.gov/mads/rdf/v1#Authority",
"http://www.w3.org/2004/02/skos/core#Concept",
"http://www.w3.org/2004/02/skos/core#Concept"
],
http://www.loc.gov/mads/rdf/v1#authoritativeLabel: [
{
@language: "en",
@value: "English"
},
{
@language: "de",
@value: "Englisch"
}
],
http://www.w3.org/2004/02/skos/core#prefLabel: [
{
@language: "en",
@value: "English"
},
{
@language: "de",
@value: "Englisch"
}
]
},
```

However, this doesn't contain a mapping to https://tools.ietf.org/html/bcp47, which is used to record the language for an RDF literal.

For example, for English the code is `en`.

@michelleif How should this be handled?

**Comment by michelleif** [comment]
can't we just use the @language from id.loc.gov? @sfolsom understands this better, and may want to comment

**Comment by justinlittman** [comment]
The @language is the language of the label, not the language itself. Thus @language=en means that the label "english" is in english.
________________________________

**Comment by sfolsom** [comment]
I'm not sure why LC didn't use ISO codes directly like the RDF spec outlines. Perhaps @kefo would know. 

Not to balloon this into a big thing, but because the language tag is optional, how does the profile direct the app to allow the cataloger to decide to add the tag?

**Comment by kefo** [comment]
> I'm not sure why LC didn't use ISO codes directly like the RDF spec outlines.

Hopefully, we do, but I can't rule it out.  We've had explicit discussions about assigning literals specific language tags and going with the two-letter codes, as is recommended in the spec.  Where are you seeing otherwise? 

So we might have this when describing the language of a literal (though most times there is no language tag at all):  
`<> bf:responsibilityStatement "Scala editore"@it;`

If I recall the recommendation correctly, one should first try to find a two-letter code from [ISO-639-1](http://id.loc.gov/vocabulary/iso639-1) and, failing that, use a three-code from [ISO-639-2](http://id.loc.gov/vocabulary/iso639-2) or another ISO 639 when describing the language of a literal (per BCP47).

But if you are trying to capture the language of the resource, we would have this: 
`<> bf:language <http://id.loc.gov/vocabulary/languages/ita>;`

Unless I can add something more, I'll back out of this but I'll depart with two observations:

1) From reading this ticket, I'm not clear if this is a display or transformation issue related to the language tag of a literal or somehow related to the bf:language property or something else altogether and I wonder if perhaps not everyone is clear about each other's meaning.  Or, I could say, I wonder if each here is as unclear as I am about the issue under discussion.  (It's probably me, but maybe not.)
2) I wonder how many emails this poor GitHub user has received today:  https://github.com/language

**Comment by kefo** [comment]
Oh , I just realized that this is the devil's issue.  Maybe that explains the chaos....

**Comment by kirkhess** [comment]
The literal-lang feature @thisismattmiller implemented uses the ISO639-1 language codes and ISO 15924 scripts: http://bibframe.org/verso/api/configs?filter[where][configType]=literalLangData, the language files are in github here: https://github.com/lcnetdev/verso/tree/master/data/vocabularies
It also has a mapping from 1 to 2 and script detection. 

There's an example in the Monograph (Non-Latin): Instance Statement of Responsibility property
http://bibframe.org/bfe/test.html
