### ISSUE TITLE
Move Save & Publish and Cancel Buttons to Editor Component 

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia_editor#679]
The current  UI requires the cataloger to press the **Preview RDF** to display the current RDF graph with two buttons **Cancel** and **Save &amp Publish** in order to click again on the **Save &amp Publish** to display the `GroupChoiceModal`. New design moves the **Cancel** and **Save &amp Publish** button to the Editor route.

See below for an example:
![savecancelpreview](https://user-images.githubusercontent.com/71847/59228109-39a44b80-8b94-11e9-8a8c-b8383215770f.png)

**Comment by jgreben** [comment]
FWIW, I don't think the "Cancel" button would go there...

**Comment by jgreben** [comment]
@michelleif @astridu @jermnelson question: should the button be _moved from_ the preview modal, or just _added to_ the main editor page? The reason I ask is because the original design had the text "If this looks good, then click Save and Publish" so should wording that be moved or removed, or handled in a different way?

**Comment by astridu** [comment]
I assume just added to the main editor page because if the user previews, then they should be able to save and publish from the preview. I think the goal of putting the save and publish on the page itself is to prevent 1 click for those users who don't need to preview. Thanks!
