### ISSUE TITLE
Linked Data Editor - Closes when trying to select a look-up entity

### ISSUE THREAD

**Issue by mmcgee** [LD4P/sinopia_editor#712]
In stage - select sinopia:resourceTemplate:bf2:Monograph:Work Under "Primary Contribution" select "Primary contributor" > "Person" > "Search LCNAF"  > type name in look-up "Twain, Mark" and try to select an entity.  Editor page unexpectedly closes and the entity is not selected.  Similar behavior with other QA look-ups in different profiles and with different source look-ups.

**Comment by michelleif** [comment]
@mmcgee I'm trying to look at the resource template "harvard:RT:bf2:Work:DigitalMap" to see how it's set up. When I look at the one in Harvard's github profile repo (https://github.com/LD4P/sinopia_sample_profiles/tree/master/cohort-profiles/Harvard), I think I am seeing an older version of the profile, because in the github one, the "Form of Work" resource template is referring to "sinopia:resourceTemplate:bf2:Form" , not "harvard:resourceTemplate:bf2:Form:DigitalMap"

could you upload here the latest resource template "harvard:RT:bf2:Work:DigitalMap", the same one you've loaded into stage, so I can see the actual RT JSON?

**Comment by mmcgee** [comment]
@michelleif apologies, uploaded now: https://github.com/LD4P/sinopia_sample_profiles/blob/master/cohort-profiles/Harvard/Harvard%20BIBFRAME%202.0%20Form%20-%20Digital%20Map.json  

Thanks for looking, maybe I missing something

**Comment by michelleif** [comment]
@mmcgee I need this: harvard:RT:bf2:Work:DigitalMap

**Comment by michelleif** [comment]
@mmcgee never mind I see you updated that one in github too

**Comment by michelleif** [comment]
I don't see anything amiss in the templates but I do notice that if I'm here harvard:RT:bf2:Work:DigitalMap and open Form of Work, and try to delete the default value (not trying to search for an additional value), I get the blank screen.

**Comment by michelleif** [comment]
here's a test Profile  that might help isolate the problem
[a profile to test blank screen issues.json.txt](https://github.com/LD4P/sinopia_editor/files/3291450/a.profile.to.test.blank.screen.issues.json.txt)

open the template test:RT:blankscreen. (it refers to another resource template test:RT:blankscreennested, which has one field, and it's a lookup). (both templates are in the profile for easy uploading)

When I open the main RT, then the nested one, I can look up successfully (example lookup "water") but when I select the result I want, I get the blank screen.

now if I open just the referenced RT on its own (test:RT:blankscreennested) I can successfully lookup and select with no problem.

it doesn't seem that the default is an issue, since the test example has no defaults.

it seems to be something with the nesting.

**Comment by jgreben** [comment]
@michelleif just looking at the profile itself I think I know what is going on. It's the same as https://github.com/LD4P/sinopia_editor/pull/684 except this time there is no defaultURI to fall bask to when there is no defaultLIteral. I will add a condition to check for this.
