### ISSUE TITLE
when a resource template has a property template with the same property URI as the preceding property template, the placeholder text for the second field incorrectly uses the property label for the first field

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#765]
example template on stage showing this:
test:repeated:tooltips
there's one Resource Template with 2 Property Templates;
both use propertyURI http://id.loc.gov/ontologies/bibframe/geographicCoverage
(yes, there are use cases for this)
the first field has propertyLabel "Geographic Coverage 1"
the second field has propertyLabel "Geographic Coverage 2"
yet the light-colored placeholder text (the text in the entry box) says "Geographic Coverage 1" for both fields
![Screen Shot 2019-06-18 at 2 15 07 PM](https://user-images.githubusercontent.com/23069165/59720345-747d3380-91d3-11e9-93e5-b07b66bb8979.png)
these fields are both literals. I also tested with the first field being a lookup and the second a literal, both with same propertyURI, and had the same problem

NOTE: an easy way to "fix" this might be to remove placeholder text altogether. There is no requirement for it that I know of.

**Comment by michelleif** [comment]
here's a profile containing the example template
[test profile for repeated property uris.json.txt](https://github.com/LD4P/sinopia_editor/files/3308448/test.profile.for.repeated.property.uris.json.txt)

**Comment by justinlittman** [comment]
Having repeating property templates (that is, multiple property templates with the same property URI) is not compatible with our current approach for persisting to RDF. When persisting to RDF the property URI is used as the predicate of the triple (that is, it is used as the key). Thus, in the case when there are repeating property templates which property template was used is lost on persistence and when loading, we will not be able to determine which of the repeated property templates to associate the value with.

The correct solution is for a resource template to not allow repeating property templates. Given that resource templates can't be changed, the next best approach is to simply ignore repeating property templates (that is, only use the first property template).

**Comment by CECSpecialistI** [comment]
Repeated property templates are needed for cataloging workflows for multiple reasons. The most frequent use we have for this is including a literal-type property template as a duplicate to a lookup-type property template, for cases where lookups fail (they will frequently, since everyone and everything in the world isn't included in the QA vocabularies). We need to be able to put something in for entities that are not yet in the vocabularies we are using. It isn't cataloging policy to create authorities for everything; where there is no conflict, we rely on unique strings. Unless we can automate the creation of URI's, it isn't sustainable to ask catalogers to create URI's for everything that isn't in the QA. We also might want different default values for different formats for the same property templates. I can also see a situation in which both a lookup PT and a literal PT might be used and given values in the same RT. Say one contributor is in the LC name authority file, and another is not. We would use a lookup for one contributor, and a literal using the same property for the other. Disallowing repeated PT's, or ignoring them, would force us to abandon most lookups in our profiles in favor of simply turning any lookup that may conceivably fail into a literal to ensure that the property can be used in cataloging.

**Comment by jcoyne** [comment]
Rather than two separate templates, one for lookup and one for a literal, is it possible that we create a template to support lookup and literal values?

**Comment by michelleif** [comment]
yes @jcoyne we need that, a property template ("field") that would be a lookup but would allow the cataloger the alternative of manually pasting/typing in a URL if they didn't find what they needed in the lookup. This is high priority because currently people are setting up RTs with duplicate fields to allow for lookup, then if lookup doesn't satisfy, a separate field for manual entry. Shall I make a new ticket requesting this? I don't know that it has to be a separate "type", perhaps we can make it simple and just say that "lookup" always offers option of manual entry, as a start. rather than trying to get more sophisticated and allow profile creator to say "on this field, only a result from a lookup is allowed, but on this other field, a manual entry is ok too".

**Comment by CECSpecialistI** [comment]
@jcoyne yes, as @michelleif says, this would be a good solution. Catalogers need to be able to paste/type in a URI or a text string for any lookup that could possibly fail.

**Comment by michelleif** [comment]
we're not allowing multiple property templates with same property URI so this is no longer a bug
