### ISSUE TITLE
when saving RDF from preview, user should see verification that it works and should get the URI

### ISSUE THREAD

**Issue by ndushay** [LD4P/sinopia_editor#766]
right now, the only way to see is by clicking "preview RDF" again and noting that there is now a URI as the subject where previously it was empty.

**Comment by jermnelson** [comment]
I think @astridu should weigh in on the design implications of this ticket. I think once we when have a URI that it should be displayed in the editor tab.

**Comment by astridu** [comment]
Could I see a screenshot of what you are talking about? I can't get to this page on development.

**Comment by jermnelson** [comment]
Hi @astrid, when you open a resource template (in this case the sinopia:resourceTemplate:bf2:WorkTitle) and first click on the **Preview RDF**, you'll get the following display using a relative URI `<>` in the RDF subject role:
![Screen Shot 2019-06-19 at 3 15 49 PM](https://user-images.githubusercontent.com/71847/59800974-25073800-92a5-11e9-9998-6e3ba55a3e7d.png)


From the modal, if you click the **Save &amp; Publish** button and select a group, the RDF is saved back to Trellis and if you open the **Preview RDF** modal again, you can see the Trellis URI (`<https://trellis.development.sinopia.io/repository/stanford/6b22feb6-c35f-462a-94d0-e8e5700fb75a>`) replaced the relative URI:
![Screen Shot 2019-06-19 at 3 17 28 PM](https://user-images.githubusercontent.com/71847/59801517-9f37bc80-92a5-11e9-9668-90d1512ab9be.png)

Once we have the Trellis URI, we would like it to appear on the Editor tab in some fashion so the user knows the URI to retrieve the RDF instead of needing to click on the **Preview RDF** to see the RDF.

Hope this helps!

**Comment by astridu** [comment]
Thank you for the explanation! Is it ok to have it on the page under the title? There should only be 1 URI, correct? Would it help to be in proximity to any of the fields, or is it important enough to warrant being at the top of the page?
![image](https://user-images.githubusercontent.com/42216982/59810823-d913bd80-92bb-11e9-8d95-8c73f8d5f702.png)

**Comment by jermnelson** [comment]
> Thank you for the explanation! Is it ok to have it on the page under the title? There should only be 1 URI, correct? Would it help to be in proximity to any of the fields, or is it important enough to warrant being at the top of the page?

I think having the URI under the title is fine. I would be interested in hearing @michelleif opinion.

**Comment by michelleif** [comment]
might be useful to preface it with a label: "URI for this resource". 

so that it's clear what this URI is. It's not the URI of the template, for example.

"URI for this resource" would have a blank following it, until the user saves, and then we would show the URI.

on a side note, once user does "Save & Publish", does the "Save & Publish" button become inactive until they change / add more data?

**Comment by astridu** [comment]
Like this?
![image](https://user-images.githubusercontent.com/42216982/59876693-209c5700-9359-11e9-9d7b-d3ef4d638944.png)

**Comment by michelleif** [comment]
yes please
