### ISSUE TITLE
InputLiteral component should retrieve propertyTemplate from redux state via reduxPath

### ISSUE THREAD

**Issue by ndushay** [LD4P/sinopia_editor#849]
analogous to issue #694 (for InputListLOC) and to 5a0090af  

The InputLiteral component currently uses a combination of propertyTemplate passed in as prop and redux state.  propertyTemplate should be derived from the reduxPath using the stored Resource Templates in the entities object in the Redux state.

**Comment by justinlittman** [comment]
Looks like this was done in https://github.com/LD4P/sinopia_editor/commit/29f469665a627f725ae2f3bf524af2da0e6f496e#diff-c8159322c93a06854f45e72e68ffdfd3 and undone in https://github.com/LD4P/sinopia_editor/commit/433ac47883262048c6e639dfe430e616073b9de0#diff-c8159322c93a06854f45e72e68ffdfd3.

Will consult with @jmartin-sul.

**Comment by jmartin-sul** [comment]
discussed on a call w/ @justinlittman, but for posterity's sake, the motivation for the undoing commit was this issue:  https://github.com/LD4P/sinopia_editor/issues/765

since the parent component already had the right property template, and the lookup from the redux store only matched on `propertyURI`, the first matching property template would always be returned, resulting in the wrong placeholder text (because another/later property template with the same `propertyURI` was the one that was actually desired).

@justinlittman thinks the right thing to do to address both #765 and this issue would be to pass down the index of the desired property template (and maybe only lookup based on index, instead of using `propertyURI` at all).

**Comment by justinlittman** [comment]
Upon further reflection and discussion with @jermnelson and based on https://github.com/LD4P/sinopia_editor/issues/765#issuecomment-507663862, I think the correct approach is to revert to the previous behavior of loading based on property URI.

In addition, as described in that comment, repeated property templates should be ignored.
