### ISSUE TITLE
when cataloger enters a literal where a URI is expected, give cataloger some kind of feedback telling them to enter a URI

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#944]
in DEV, I made a Resource Template my:resourcetemplate
with the first property template of type = resource, and no target/nested RT specified, so it expects the cataloger to enter a URI

when cataloger sees this field, it looks like a literal field. but when cataloger enters a literal value, and hits enter, the value is not "entered" like one would expect nor does it show up in preview

the cataloger has no way of knowing they're supposed to be entering a URI. 

can we tell them somehow? I don't think a tooltip is best solution because profile creator may already have added their own tooltip (remark) specific to this field

**Comment by michelleif** [comment]
Astrid will have user input and recommendation by Monday July 22

**Comment by astridu** [comment]
Users preferred having the text "Enter a URI" above the box rather than as a watermark. However, they were ok with the instruction as a watermark as well. Let's go w/the watermark since that is the standard pattern for now.  
Also, the error message was clear to them. 
![image](https://user-images.githubusercontent.com/42216982/61562091-58b0bb80-aa25-11e9-8020-2bfc4e7e0b04.png)

**Comment by michelleif** [comment]
results of Astrid user testing: users preferred having a message above the entry box vs. in the box itself (since once they start typing, the message would go away). 

Decided to put the validation/error message below the field, like our other validation failure messages.
